hotplug: wifi: Configure one device instead of all devices
/sbin/wifi config was called each time a device hotplug event fires. The
mac80211.sh script would then compare /sys/class/ieee80211/* (phyN) and
the current /etc/config/wireless config and configure all unconfigured
phys. Instead take the hotplug device phy name from DEVICENAME and only
configure that device.

This avoids a race condition where two devices are hotplugged at once
and each parallel invocation of the wifi script will try to configure
both of the devices.

Running `wifi config` will still configure all devices, as before.
Running `wifi config phy0` will configure only the phy0 device.

diff --git a/package/network/config/wifi-scripts/files/sbin/wifi b/package/network/config/wifi-scripts/files/sbin/wifi
--- a/package/network/config/wifi-scripts/files/sbin/wifi
+++ b/package/network/config/wifi-scripts/files/sbin/wifi
@@ -181,7 +181,9 @@ wifi_config() {
 
 	for driver in $DRIVERS; do (
 		if eval "type detect_$driver" 2>/dev/null >/dev/null; then
-			eval "detect_$driver" || echo "$driver: Detect failed" >&2
+			# if an argument is provided, configure only that device.
+			# Otherwise, configure all unconfigured devices.
+			eval "detect_$driver" $1 || echo "$driver: Detect failed" >&2
 		else
 			echo "$driver: Hardware detection not supported" >&2
 		fi
@@ -261,7 +263,7 @@ scan_wifi
 case "$1" in
 	down) wifi_updown "disable" "$2";;
 	detect) wifi_detect_notice ;;
-	config) wifi_config ;;
+	config) wifi_config "$2";;
 	status) ubus_wifi_cmd "status" "$2";;
 	isup) wifi_isup "$2"; exit $?;;
 	reload) wifi_reload "$2";;
